name: AdvancedBounty
main: wockkinmycup\advancedbounty\Loader
api: 5.0.0
version: 1.0.0
author: woccck

permissions:
  advancedbounty.default:
    default: true
  advancedbounty.admin:
    default: op